version: '3.5'
services:
  bedrock-mysql:
    image: 'mysql:8.0.32'
    container_name: bedrock-mysql
    working_dir: /application
    volumes:
      - 'mysql:/var/lib/mysql'
      - './docker/mysql:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_ROOT_PASSWORD=bedrock
      - MYSQL_DATABASE=bedrock
      - MYSQL_USER=bedrock
      - MYSQL_PASSWORD=bedrock
    ports:
      - '6043:3306'

  bedrock-webserver:
    image: 'nginx:alpine'
    container_name: bedrock-webserver
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './docker/nginx/certs:/etc/nginx/certs'
    ports:
      - '6044:80'
      - '6443:443'

  bedrock-php-fpm:
    build: docker/php-fpm
    container_name: bedrock-php-fpm
    working_dir: /application
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - '.:/application'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
      - './docker/php-fpm/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini'

  bedrock-mailhog:
    image: 'mailhog/mailhog'
    container_name: bedrock-mailhog
    volumes:
      - 'mailhog:/maildir'
    ports:
      - '6045:8025'
volumes:
  mysql:
  mailhog:

networks:
  default:
    name: bedrock
